include(gametypes/gt_hns)
include(gametypes/gt_dem)
include(gametypes/gt_inf)
include(gametypes/gt_ctf)
include(gametypes/gt_dm)
include(gametypes/gt_tdm)
include(gametypes/gt_elim)
include(gametypes/gt_hnz)
include(gametypes/gt_csinf)
# include(gametypes/gt_mm)
include(gametypes/gt_vip)
include(gametypes/gt_prop)
include(gametypes/gt_gg)
